name: JFrog CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    env:
      JFROG_URL: "https://andrewrjpd1.jfrog.io"
      JFROG_OIDC_PROVIDER_NAME: "github"
      JFROG_OIDC_AUDIENCE: "jfrog"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Use a stable older version of the setup action
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3 # Using v3 instead of v4

      # 2. Add an EXPLICIT server configuration step
      - name: Configure JFrog Server
        run: |
          jf c add temp-server --url=$JFROG_URL --oidc-provider-name=$JFROG_OIDC_PROVIDER_NAME --oidc-audience=$JFROG_OIDC_AUDIENCE
          jf c use temp-server

      # 3. The debug step to verify the configuration
      - name: Show JFrog CLI Config
        run: jf c show

      # 4. Upload the artifact
      - name: Upload Artifact to Artifactory
        run: |
          echo "Hello from GitHub Actions!" > my-file.txt
          jf rt u "my-file.txt" "my-generic-repo/"
          echo "Upload complete!"
