name: JFrog CI Workflow (Username/Password Auth)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      # Configure JFrog CLI with your hardcoded credentials
      - name: Configure JFrog Server
        run: |
          jf c add temp-server --url="https://andrewrjpd1.jfrog.io" --user="andrewr@jfrog.com" --password="BigCountry1!" --overwrite
          jf c use temp-server
        
      # Debug step to verify the configuration
      - name: Show JFrog CLI Config
        run: jf c show

      # Upload the artifact
      - name: Upload Artifact to Artifactory
        run: |
          echo "Hello from GitHub Actions!" > my-file.txt
          jf rt u "my-file.txt" "my-generic-repo/"
          echo "Upload complete!"
