name: "Build and Push Docker Image with OIDC"
on: push

permissions:
  id-token: write
  contents: read

env:
  # The base URL of your JFrog Platform
  JFROG_URL: "https://andrewrjpd1.jfrog.io"
  # The specific Artifactory Docker registry URL for login
  ARTIFACTORY_REGISTRY: "andrewrjpd1.jfrog.io"
  # Your target Docker repo in Artifactory
  ARTIFACTORY_DOCKER_REPO: "docker-local"
  # Example image name and tag
  DOCKER_IMAGE_NAME: ${{ github.repository }}
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Setup JFrog CLI and authenticate via OIDC
      - name: Setup JFrog CLI
        id: setup_jfrog # Give the step an ID to reference its outputs
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: github

      # 2. Setup Docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Artifactory Docker registry
      # Use the access token generated by the 'setup_jfrog' step
      - name: Log in to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACTORY_REGISTRY }}
          username: ${{ steps.setup_jfrog.outputs.oidc-user-name }}
          password: ${{ steps.setup_jfrog.outputs.oidc-access-token }}

      # 4. Build and tag your Docker image
      - name: Build and Tag Docker Image
        run: |
          docker build -t "${{ env.ARTIFACTORY_REGISTRY }}/${{ env.ARTIFACTORY_DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}" .

      # 5. Push the Docker image with JFrog CLI
      - name: Push Docker Image to Artifactory
        run: |
          jf rt docker-push "${{ env.ARTIFACTORY_REGISTRY }}/${{ env.ARTIFACTORY_DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}" ${{ env.ARTIFACTORY_DOCKER_REPO }} --build-name=${{ github.workflow }} --build-number=${{ github.run_number }}
          jf rt build-publish ${{ github.workflow }} ${{ github.run_number }}
