name: JFrog CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    env:
      JFROG_URL: "https://andrewrjpd1.jfrog.io/artifactory"
      JFROG_OIDC_PROVIDER_NAME: "github" # Must match the provider name in JFrog UI
      JFROG_OIDC_AUDIENCE: "jfrog"      # Must match the audience in JFrog UI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # The setup action will now read the env vars and handle the entire OIDC exchange
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      # The debug step to verify the action worked
      - name: Show JFrog CLI Config
        run: jf c show

      # The upload step
      - name: Upload Artifact to Artifactory
        run: |
          echo "Hello from GitHub Actions!" > my-file.txt
          jf rt u "my-file.txt" "my-generic-repo/"
          echo "Upload complete!"
